### ISSUE TITLE
Configuration cache broken

### ISSUE THREAD

**Issue by lepicekmichal** [GradleUp/auto-manifest#13]
Version 1.1.0 broke configuration cache.
org.gradle.unsafe.configuration-cache=true
https://docs.gradle.org/current/userguide/configuration_cache.html

**Comment by tasomaniac** [comment]
I actually did not do anything special to support the configuration cache. I was actually planning to look if the plugin works well with it or not. And that's something I have not done myself. 

It is good to hear that the first stable Version actually supported it. 

Could you give me more details on what is broken? Any error message you see?

**Comment by lepicekmichal** [comment]
```
Configuration cache problems found in this build.

150 problems were found storing the configuration cache, 75 of which seem unique.
- Task `:shared:accountNavigation:generateAndroidManifest` of type `com.gradleup.auto.manifest.GenerateManifestTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:shared:action:generateAndroidManifest` of type `com.gradleup.auto.manifest.GenerateManifestTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
```

https://docs.gradle.org/7.4.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

**Comment by tasomaniac** [comment]
This actually did not change. It was the same on 1.0. It could be because I now used the latest Gradle version to publish the plugin. 

Anyways, I think I need to support the configuration cache with this project. I will take a look quickly. This should not be too hard to fix. 

Thanks for opening the issue.

**Comment by tasomaniac** [comment]
Wow, this was caused by using `onlyIf {}` function. After all these years working with Graldle, it can still surprise me with how easy it is to shoot myself in the foot with such simple things

Reference: https://github.com/gradle/gradle/issues/16080
